services:
  backend-svc:
    image: ghcr.io/rum-people/backend-svc:<commit-hash>
    restart: unless-stopped
    depends_on:
      backend-svc-pgdb:
        condition: service_healthy

  backend-svc-pgdb:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=backend-svc
      - POSTGRES_PASSWORD=backend-svc
      - POSTGRES_DB=backend-svc
    volumes:
      - backend-svc-pgdb-data:/var/lib/postgresql/data    

  frontend:
    image: ghcr.io/rum-people/frontend-svc:<commit-hash>
    restart: unless-stopped
    volumes:
      - ./configs/frontend.js:/usr/share/nginx/html/static/env.js
    ports:
      - "7000:80"


volumes:
  backend-svc-pgdb-data: